@startuml
'https://plantuml.com/sequence-diagram

autonumber
autoactivate on

Actor "Client" as client
participant "CreateRoomOverlay" as CRO
participant "Open Trivia DB" as trivia
participant "Supabase" as supabase

note over client, supabase: The user selects the "CREATE" button, on the home page, inputs the fills the required information and presses the "CREATE" button

client -> CRO: Presses the "CREATE" button
    CRO -> CRO: generateTriviaURL(question_number, question_category, question_difficulty, question_type)
    return trivia_url

    CRO -> CRO: requestTrivia(room_token, trivia_url)
            CRO -> trivia: fetch(url)
            trivia --> CRO:

            CRO -> supabase: insert({room, questions})
            supabase --> CRO:
        return

    CRO -> CRO: createRoom(room_token, number_of_players, trivia)
        CRO -> CRO: router.navigate()
        return
    return
CRO --> client: Sends user to Waiting Room

@enduml