@startuml
'https://plantuml.com/sequence-diagram

autonumber
autoactivate on

Actor "Client" as client
participant "UI" as ui

note over client: The user selects the "JOIN" button, on the home page, and fills the required information

client -> ui: Presses the "JOIN" button
ui --> client: Sends user to Waiting Room

@enduml