@startuml
'https://plantuml.com/sequence-diagram

autonumber

Actor "User" as user
participant ":System" as sys

user -> sys: Click Home Page navbar button
user <-- sys: Show Home Page Screen

user -> sys: Click on the profile image
user <-- sys: Show overlay to change image

user -> sys: Select image
user <-- sys: Save profile image

@enduml