@startuml
'https://plantuml.com/use-case-diagram
left to right direction
title Use Case Diagram

actor "User" as usms
rectangle "Home Page Screen" {
    usecase "1. Join game session" as UCMS1
    usecase "2. Create game room" as UCMS2
    usecase "3. Change user profile picture" as UCMS3
}
usms --> UCMS1
usms --> UCMS2
usms --> UCMS3

actor "User" as uslb
rectangle "Leaderboard Screen" {
    usecase "1. Change between user and global leaderboard" as UCLB1
    usecase "2. Share game result" as UCLB2
}
uslb --> UCLB1
uslb --> UCLB2

actor "User" as usss
rectangle "Settings Screen" {
    usecase "1. Change profile picture" as UCSS1
    usecase "2. Change username" as UCSS2
    usecase "3. Copy token to clipboard" as UCSS3
    usecase "4. Change app theme" as UCSS4
    usecase "5. Change app language" as UCSS5
    usecase "6. Export user data" as UCSS6
    usecase "7. Logout" as UCSS7
}
usss --> UCSS1
usss --> UCSS2
usss --> UCSS3
usss --> UCSS4
usss --> UCSS5
usss --> UCSS6
usss --> UCSS7


@enduml