@startuml
'https://plantuml.com/class-diagram

class User {
    username: Text
    user_token: Text
    profile_picture: Text
    games_played: Number
    language: Text
}

class GameScore {
    _id: Text
    rank: Number
    game_date: Text
    score: Number
    time: Number
}

class LeaderboardEntry {
    room_token: Text
}

class PlayerScore {
    name: Text
    points: Number
}

class Room {
    id: Number
    room_token: Text
}

class TriviaObject {
    type: Text
    difficulty: Text
    category: Text
    question: Text
    correct_answer: Text
    incorrect_answers: Array
}

User "1..8" -- "0..1" Room
Room "1" -- "1..50" TriviaObject
Room "1" -- "1" GameScoreMetadata
User "1" -- "*" GameScore
GameScore "1..8" -- "1" LeaderboardEntry
LeaderboardEntry "1" -- "1..8" PlayerScore

@enduml