@startuml
'https://plantuml.com/sequence-diagram

autonumber
autoactivate on

Actor "Client" as client
participant "SettingsScreen" as ss

note over client, ss: The user goes to the Settings screen and clicks the "LOGOUT" button

client -> ss: Clicks the "LOGOUT" button
    ss -> ss: dispatch(logout())
    ss --> ss
    ss -> ss: storage.clearAll()
    ss --> ss
ss --> client: Shows login screen

@enduml