@startuml
'https://plantuml.com/sequence-diagram

autonumber
autoactivate on

Actor "Client" as client
participant "UI" as ui

note over client, ui: The user goes to the Leaderboard screen, clicks on a score and presses the "SHARE" button

client -> ui: Presses the "SHARE" button
    ui -> ui: App takes a screenshot of the score's view
    ui --> ui
ui --> client: Intent to share the screenshot
@enduml