@startuml
'https://plantuml.com/sequence-diagram

autonumber

Actor "User" as user
participant ":System" as sys

user -> sys: Enter Leaderboard Screen
user <-- sys: Shows 25 users or global highest scores

user -> sys: Click on a game result
user <-- sys: Opens game result overlay

@enduml