@startuml
'https://plantuml.com/sequence-diagram

autonumber

Actor "User" as user
participant ":System" as sys

user -> sys: Click Settings navbar button
user <-- sys: Show Settings Screen

user -> sys: Chooses the app language
user <-- sys: Updates the app language

@enduml